#!/bin/bash

# Copy the contents of this to your shell config file of choice (eg. ~/.profile, 
# ~/.bashrc, etc). In addition to the usual aws-cdk dependencies, this app relies
# on credentials exported to the shell environment. We use direnv for that here
# but you can use whatever you want as long as it sets environment variables.



# Command line autocompleters
complete -C '/usr/local/bin/aws_completer' aws

# Setup Python environment
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

export PATH="/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:${PATH}"
export PYENV_VIRTUALENV_INIT=1

_pyenv_virtualenv_hook()
{
  local ret=$? 
  if [ -n "$VIRTUAL_ENV" ]; then 
    eval "$(pyenv sh-activate --quiet || pyenv sh-deactivate --quiet || true)" || true 
  else 
    eval "$(pyenv sh-activate --quiet || true)" || true 
  fi 
  return $ret 
}; 

if ! [[ "$PROMPT_COMMAND" =~ _pyenv_virtualenv_hook ]]; then 
  PROMPT_COMMAND="_pyenv_virtualenv_hook;$PROMPT_COMMAND"; 
fi


# Setup direnv for directory environment variables
eval "$(direnv hook bash)"

# A helpful alias when you're modifying .envrc often
function reload-direnv {
  direnv allow && direnv reload
}

